# Generated by Django 2.2 on 2022-05-03 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('zip_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=30)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_Number', models.BigIntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_untill', models.DateTimeField()),
                ('creattion_date', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('completed', 'Completed')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
