# Generated by Django 2.2 on 2022-05-03 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_untill',
            new_name='date_until',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='creattion_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('completed', 'Completed')], max_length=100),
        ),
    ]
